export interface Product {
  id: string
  name: string
  description: string
  category: string
  country?: string
  activeDays: number
  price: number // Now in Nigerian Naira (₦)
  originalPrice?: number
  rating: number
  reviews: number
  image: string
  features: string[]
  inStock: boolean
  stock: number // Added stock quantity field
}

export const products: Product[] = [
  // Facebook Accounts
  {
    id: "fb-usa-pure-001",
    name: "USA PURE FACEBOOK",
    description: "Premium USA Facebook account with complete verification and clean history",
    category: "facebook",
    country: "United States",
    activeDays: 365,
    price: 40000, // Converted to Nigerian Naira
    originalPrice: 56000,
    rating: 4.9,
    reviews: 156,
    image: "/facebook-logo-blue-social-media.png",
    features: ["Pure USA account", "Complete verification", "Clean history", "Email included"],
    inStock: true,
    stock: 25,
  },
  {
    id: "fb-canada-001",
    name: "CANADA FACEBOOK",
    description: "Verified Canadian Facebook account with active profile",
    category: "facebook",
    country: "Canada",
    activeDays: 270,
    price: 48000,
    originalPrice: 64000,
    rating: 4.8,
    reviews: 89,
    image: "/facebook-logo-blue-social-media.png",
    features: ["Canadian verified", "Active profile", "Friends included", "Marketplace access"],
    inStock: true,
    stock: 18,
  },
  {
    id: "fb-australia-001",
    name: "AUSTRALIA FACEBOOK",
    description: "Australian Facebook account with complete profile setup",
    category: "facebook",
    country: "Australia",
    activeDays: 180,
    price: 52000,
    rating: 4.7,
    reviews: 67,
    image: "/facebook-logo-blue-social-media.png",
    features: ["Australian account", "Profile complete", "Phone verified", "Active timeline"],
    inStock: true,
    stock: 12,
  },
  {
    id: "fb-germany-001",
    name: "GERMANY FACEBOOK",
    description: "German Facebook account with EU verification",
    category: "facebook",
    country: "Germany",
    activeDays: 200,
    price: 45000,
    originalPrice: 60000,
    rating: 4.6,
    reviews: 43,
    image: "/facebook-logo-blue-social-media.png",
    features: ["German verified", "EU compliant", "Active friends", "Marketplace enabled"],
    inStock: true,
    stock: 8,
  },
  {
    id: "fb-random-001",
    name: "RANDOM FACEBOOK",
    description: "Random country Facebook account with basic verification",
    category: "facebook",
    country: "Various",
    activeDays: 90,
    price: 24000,
    rating: 4.3,
    reviews: 234,
    image: "/facebook-logo-blue-social-media.png",
    features: ["Random country", "Basic verification", "Active account", "Email access"],
    inStock: true,
    stock: 45,
  },

  // Premium Video / VPNs
  {
    id: "hma-vpn-001",
    name: "HMA VPN",
    description: "HMA VPN premium account with global server access",
    category: "premium-vpn",
    activeDays: 30,
    price: 12800,
    originalPrice: 19200,
    rating: 4.5,
    reviews: 89,
    image: "/hma-vpn-logo.png",
    features: ["Global servers", "No logs policy", "Fast speeds", "Multiple devices"],
    inStock: true,
    stock: 35,
  },
  {
    id: "surfshark-vpn-001",
    name: "SURFSHARK VPN",
    description: "Surfshark VPN premium with unlimited devices",
    category: "premium-vpn",
    activeDays: 30,
    price: 9600,
    originalPrice: 16000,
    rating: 4.7,
    reviews: 156,
    image: "/surfshark-vpn-logo.png",
    features: ["Unlimited devices", "CleanWeb feature", "Whitelister", "MultiHop"],
    inStock: true,
    stock: 42,
  },
  {
    id: "nord-vpn-001",
    name: "NORD VPN",
    description: "NordVPN premium account with advanced security features",
    category: "premium-vpn",
    activeDays: 30,
    price: 16000,
    originalPrice: 24000,
    rating: 4.8,
    reviews: 298,
    image: "/nordvpn-logo.png",
    features: ["Double VPN", "CyberSec", "Onion over VPN", "6 devices"],
    inStock: true,
    stock: 28,
  },
  {
    id: "express-vpn-001",
    name: "EXPRESS VPN",
    description: "ExpressVPN premium with fastest speeds and 94 countries",
    category: "premium-vpn",
    activeDays: 30,
    price: 20800,
    originalPrice: 32000,
    rating: 4.9,
    reviews: 445,
    image: "/expressvpn-logo.png",
    features: ["94 countries", "Fastest speeds", "Split tunneling", "5 devices"],
    inStock: true,
    stock: 15,
  },
  {
    id: "eset-vpn-001",
    name: "ESET VPN",
    description: "ESET VPN premium with antivirus integration",
    category: "premium-vpn",
    activeDays: 30,
    price: 11200,
    rating: 4.4,
    reviews: 67,
    image: "/eset-vpn-logo.png",
    features: ["Antivirus integration", "Secure browsing", "No logs", "Easy setup"],
    inStock: true,
    stock: 22,
  },
  {
    id: "ipvanish-vpn-001",
    name: "IP VANISH VPN",
    description: "IPVanish VPN premium with unlimited bandwidth",
    category: "premium-vpn",
    activeDays: 30,
    price: 14400,
    originalPrice: 20800,
    rating: 4.3,
    reviews: 134,
    image: "/ipvanish-vpn-logo.png",
    features: ["Unlimited bandwidth", "Zero logs", "SOCKS5 proxy", "10 devices"],
    inStock: true,
    stock: 31,
  },
  {
    id: "pia-vpn-001",
    name: "PIA VPN",
    description: "Private Internet Access VPN with port forwarding",
    category: "premium-vpn",
    activeDays: 30,
    price: 8000,
    originalPrice: 12800,
    rating: 4.2,
    reviews: 89,
    image: "/pia-vpn-logo.png",
    features: ["Port forwarding", "MACE ad blocker", "Open source", "10 devices"],
    inStock: true,
    stock: 38,
  },

  // USA Texting Log
  {
    id: "textplus-001",
    name: "TEXTPLUS",
    description: "TextPlus premium account with unlimited texting and calling",
    category: "usa-texting",
    country: "United States",
    activeDays: 30,
    price: 6400,
    originalPrice: 9600,
    rating: 4.1,
    reviews: 78,
    image: "/textplus-logo.png",
    features: ["Unlimited texts", "Free calls", "Custom number", "Ad-free"],
    inStock: true,
    stock: 56,
  },
  {
    id: "talkaton-001",
    name: "TALKATON",
    description: "Talkaton premium with free international calls",
    category: "usa-texting",
    country: "United States",
    activeDays: 30,
    price: 4800,
    rating: 3.9,
    reviews: 45,
    image: "/talkaton-app-logo.png",
    features: ["International calls", "SMS support", "Multiple numbers", "Call recording"],
    inStock: true,
    stock: 34,
  },
  {
    id: "old-google-voice-001",
    name: "OLD GOOGLE VOICE",
    description: "Legacy Google Voice account with established number",
    category: "usa-texting",
    country: "United States",
    activeDays: 365,
    price: 32000,
    originalPrice: 48000,
    rating: 4.6,
    reviews: 123,
    image: "/google-voice-logo.png",
    features: ["Established number", "Legacy features", "SMS & calls", "Gmail integration"],
    inStock: true,
    stock: 8,
  },
  {
    id: "new-google-voice-001",
    name: "NEW GOOGLE VOICE",
    description: "Fresh Google Voice account with new number",
    category: "usa-texting",
    country: "United States",
    activeDays: 365,
    price: 24000,
    originalPrice: 35200,
    rating: 4.4,
    reviews: 89,
    image: "/google-voice-logo.png",
    features: ["Fresh number", "Full features", "Cross-platform", "Free domestic calls"],
    inStock: true,
    stock: 18,
  },

  // Instagram
  {
    id: "ig-aged-hacked-001",
    name: "Aged Hacked Instagram with friends",
    description: "Login account on browser first — Aged Instagram account with established friend network",
    category: "instagram",
    activeDays: 180,
    price: 3509, // Exact price as specified
    rating: 4.3,
    reviews: 67,
    image: "/instagram-logo-pink.png",
    features: ["Aged account", "Established friends", "Browser login first", "Active history"],
    inStock: true,
    stock: 12,
  },

  // Legacy products converted to Naira
  {
    id: "num-us-001",
    name: "US Phone Number",
    description: "Virtual US phone number for verification and SMS reception",
    category: "foreign-numbers",
    country: "United States",
    activeDays: 30,
    price: 19200, // Converted to Naira
    originalPrice: 28800,
    rating: 4.6,
    reviews: 203,
    image: "/usa-phone-verification.png",
    features: ["SMS reception", "Voice calls", "Multiple apps", "Instant activation"],
    inStock: true,
    stock: 45,
  },
  {
    id: "num-uk-001",
    name: "UK Phone Number",
    description: "British phone number for UK-specific verifications",
    category: "foreign-numbers",
    country: "United Kingdom",
    activeDays: 30,
    price: 22400, // Converted to Naira
    rating: 4.4,
    reviews: 87,
    image: "/uk-phone-british-flag.png",
    features: ["UK carrier", "SMS & calls", "WhatsApp support", "Banking apps"],
    inStock: true,
    stock: 32,
  },
  {
    id: "netflix-001",
    name: "Netflix Premium Account",
    description: "Netflix Premium subscription with 4K streaming and multiple screens",
    category: "premium-apps",
    activeDays: 30,
    price: 12800, // Converted to Naira
    originalPrice: 19200,
    rating: 4.9,
    reviews: 312,
    image: "/netflix-streaming-premium.png",
    features: ["4K Ultra HD", "4 screens", "Download offline", "All regions"],
    inStock: true,
    stock: 67,
  },
  {
    id: "spotify-001",
    name: "Spotify Premium Account",
    description: "Spotify Premium with ad-free music and offline downloads",
    category: "premium-apps",
    activeDays: 30,
    price: 8000, // Converted to Naira
    originalPrice: 12800,
    rating: 4.8,
    reviews: 267,
    image: "/spotify-logo-green.png",
    features: ["Ad-free music", "Offline downloads", "High quality", "Unlimited skips"],
    inStock: true,
    stock: 89,
  },
]

export const categoryMap = {
  facebook: "Facebook Accounts",
  instagram: "Instagram Accounts",
  "premium-vpn": "Premium VPNs",
  "usa-texting": "USA Texting Services",
  "foreign-numbers": "Foreign Numbers",
  "premium-apps": "Premium App Logins",
  "social-media": "Social Media Accounts",
}

export const formatPrice = (price: number): string => {
  return `₦${price.toLocaleString()}`
}
